# Generated by Django 2.2.4 on 2019-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_pop',
            field=models.IntegerField(default=0),
        ),
    ]
